import { useEffect, useMemo, useState } from "react";
import axios from "axios";
import { Link } from "react-router-dom";
import { Button, Form, Modal, Badge, Alert } from "react-bootstrap";
import { AreaChart, Bell, CheckCircle2, ChevronLeft, ClipboardList, Download, LayoutDashboard, Menu, MessageSquare, Moon, MoreHorizontal, Plus, Search, Settings, Star, Sun, Ticket, Users, UserPlus } from "lucide-react";
import "./UserCrmDashboard.css";

const API_URL = process.env.REACT_APP_API_URL || "http://localhost:5000/api";
const authHeader = () => ({ headers: { Authorization: `Bearer ${localStorage.getItem("token")}` } });
const statuses = ["All", "Pending", "Assigned", "In Progress", "Resolved", "Cancelled", "Reopened"];
const statusClass = (status) => `ticket-status ${String(status).toLowerCase().replaceAll(" ", "-")}`;
const navItems = [["Dashboard", LayoutDashboard], ["Customers", Users], ["Tickets", Ticket], ["Agents", UserPlus], ["Feedback", MessageSquare], ["Analytics", AreaChart], ["Reports", ClipboardList], ["Notifications", Bell], ["Settings", Settings]];

function Metric({ icon: Icon, title, value, note, color }) { return <article className={`uc-metric ${color}`}><span className="uc-metric-icon"><Icon size={20}/></span><p>{title}</p><strong>{value}</strong><div><b>{note}</b><small>Updated just now</small></div></article>; }
function MiniChart() { return <div className="uc-line-chart"><svg viewBox="0 0 620 155" preserveAspectRatio="none"><defs><linearGradient id="userChartFill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#7355ed" stopOpacity=".3"/><stop offset="1" stopColor="#7355ed" stopOpacity="0"/></linearGradient></defs>{[24,65,106,145].map(y => <line key={y} x1="0" x2="620" y1={y} y2={y}/>) }<path d="M0 127 C54 110 77 122 117 91 S193 110 235 68 S310 85 360 60 S447 80 492 37 S570 53 620 16 L620 155 L0 155Z" fill="url(#userChartFill)"/><path d="M0 127 C54 110 77 122 117 91 S193 110 235 68 S310 85 360 60 S447 80 492 37 S570 53 620 16"/></svg><div><span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span></div></div> }
function Donut({ total, resolved }) { const pct = total ? Math.round((resolved / total) * 100) : 0; return <div className="uc-donut-layout"><div className="uc-donut" style={{ background: `conic-gradient(#7654ed 0 ${Math.max(pct, 35)}%, #efa640 ${Math.max(pct,35)}% 75%, #edf0f5 75% 100%)` }}><span><b>{total}</b><small>Total</small></span></div><div className="uc-legend"><p><i/>Resolved <b>{resolved}</b></p><p><i/>In review <b>{Math.max(total - resolved, 0)}</b></p><p><i/>Pending <b>{Math.max(total - resolved, 0)}</b></p></div></div> }

export default function HomePage({ user, onLogout }) {
  const [complaints, setComplaints] = useState([]), [error, setError] = useState(""), [search, setSearch] = useState(""), [filter, setFilter] = useState("All");
  const [active, setActive] = useState("Dashboard"), [dark, setDark] = useState(false), [collapsed, setCollapsed] = useState(false), [mobile, setMobile] = useState(false);
  const [showSettings, setShowSettings] = useState(false), [showFeedback, setShowFeedback] = useState(false), [feedback, setFeedback] = useState(""), [sent, setSent] = useState(false);
  const [updates, setUpdates] = useState(() => localStorage.getItem("complaintUpdates") !== "off");
  useEffect(() => { axios.get(`${API_URL}/complaints`, authHeader()).then(({data}) => setComplaints(data)).catch(err => setError(err.response?.data?.message || "Could not load complaints")); }, []);
  const visible = useMemo(() => complaints.filter(c => { const value = `${c.name} ${c.city} ${c.state} ${c.comment}`.toLowerCase(); return (filter === "All" || c.status === filter) && value.includes(search.toLowerCase()); }), [complaints, filter, search]);
  const resolved = complaints.filter(c => c.status === "Resolved").length, activeCount = complaints.filter(c => !["Resolved", "Cancelled"].includes(c.status)).length;
  const select = item => { if (item === "Settings") setShowSettings(true); else if (item === "Feedback") setShowFeedback(true); else setActive(item); setMobile(false); };
  const submitFeedback = e => { e.preventDefault(); if (!feedback.trim()) return; localStorage.setItem("latestFeedback", feedback.trim()); setFeedback(""); setSent(true); };
  return <div className={`user-crm ${dark ? "uc-dark" : ""} ${collapsed ? "uc-collapsed" : ""}`}>
    <aside className={`uc-sidebar ${mobile ? "open" : ""}`}><div className="uc-logo"><span><AreaChart size={20}/></span><b>Civic<span>Desk</span></b><button onClick={() => setCollapsed(!collapsed)}><ChevronLeft size={17}/></button></div><nav>{navItems.map(([name, Icon]) => <button key={name} className={active === name ? "active" : ""} onClick={() => select(name)}><Icon size={19}/><span>{name}</span>{name === "Notifications" && <i>3</i>}</button>)}</nav><div className="uc-sidebar-bottom"><Star size={17}/><div><b>Premium support</b><small>We're here to help</small></div></div></aside>{mobile && <button className="uc-scrim" onClick={() => setMobile(false)}/>}<main className="uc-main">
      <header className="uc-topbar"><button className="uc-mobile-menu" onClick={() => setMobile(true)}><Menu size={21}/></button><div className="uc-search"><Search size={18}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search tickets, reports, or activity..."/></div><div className="uc-top-actions"><span className="uc-db">Local database</span><button className="uc-icon"><Bell size={19}/><i>3</i></button><button className="uc-icon" onClick={() => setDark(!dark)}>{dark ? <Sun size={18}/> : <Moon size={18}/>}</button><button className="uc-profile" onClick={() => setShowSettings(true)}><span>{user?.name?.charAt(0)?.toUpperCase() || "U"}</span><div><b>{user?.name?.split(" ")[0] || "Citizen"}</b><small>Customer portal</small></div></button></div></header>
      <section className="uc-content"><div className="uc-welcome"><div><p>{new Date().toLocaleDateString(undefined, {weekday:"long", month:"long", day:"numeric"})}</p><h1>Welcome back, {user?.name?.split(" ")[0] || "Citizen"}</h1><small>Your support overview, all in one place.</small></div><div><Link to="/home/new-complaint"><Button><Plus size={17}/> Create ticket</Button></Link><Button variant="light" onClick={onLogout}>Logout</Button></div></div>
      {error && <Alert variant="danger">{error}</Alert>}
      {active === "Dashboard" && <><div className="uc-metrics"><Metric title="Total customers" value={complaints.length || 1} note="+12% this month" icon={Users} color="purple"/><Metric title="Open tickets" value={activeCount} note="Needs review" icon={Ticket} color="orange"/><Metric title="Resolved tickets" value={resolved} note="SLA on track" icon={CheckCircle2} color="green"/><Metric title="Pending issues" value={complaints.filter(c => c.status === "Pending").length} note="Live queue" icon={ClipboardList} color="slate"/></div>
      <div className="uc-chart-grid"><article className="uc-panel"><header><div><h2>Customer growth</h2><p>Customer registrations over the last 6 months</p></div><button><MoreHorizontal size={19}/></button></header><div className="uc-chart-value"><b>{complaints.length || 1}</b><span>↗ 12.6% from prior period</span></div><MiniChart/></article><article className="uc-panel"><header><div><h2>Ticket status</h2><p>Current complaint distribution</p></div><button><MoreHorizontal size={19}/></button></header><Donut total={complaints.length} resolved={resolved}/></article></div>
      <div className="uc-lower-grid"><article className="uc-panel"><header><div><h2>Recent activity</h2><p>Latest updates in your workspace</p></div><button className="uc-link" onClick={() => select("Tickets")}>View tickets</button></header><div className="uc-activity">{complaints.slice(0,3).map((c, index) => <div key={c._id}><i className={`dot-${index}`}/><span><b>{c.name}</b><small>{c.city || "Support"} · {c.status}</small></span><Badge className={statusClass(c.status)}>{c.status}</Badge></div>)}{!complaints.length && <p className="uc-empty">No recent tickets. Create your first ticket to get started.</p>}</div></article><article className="uc-panel uc-feedback"><header><div><h2>Recent feedback</h2><p>What customers are saying</p></div><button className="uc-link" onClick={() => setShowFeedback(true)}>Share feedback</button></header><div className="uc-feedback-card"><span>AR</span><div><b>Alex Rivera <em><Star size={12} fill="currentColor"/> 4.9</em></b><p>“Clear updates and a fast response from the support team.”</p><small>Yesterday</small></div></div></article></div>
      <article className="uc-panel uc-actions"><div><p>QUICK ACTIONS</p><h2>Keep work moving</h2><small>Manage every stage of your support request.</small></div><div><Link to="/home/new-complaint"><button><Plus size={17}/>Add customer</button></Link><Link to="/home/new-complaint"><button><Ticket size={17}/>Create ticket</button></Link><button onClick={() => select("Agents")}><Users size={17}/>Assign agent</button><button><Download size={17}/>Export report</button></div></article></>}
      {active !== "Dashboard" && <section className="uc-panel uc-workspace"><header><div><h2>{active === "Tickets" ? "My tickets" : active}</h2><p>{active === "Tickets" ? "Track and search your reported complaints." : "Your workspace is ready for the next update."}</p></div></header>{active === "Tickets" ? <><div className="uc-table-tools"><Form.Select value={filter} onChange={e => setFilter(e.target.value)}>{statuses.map(s => <option key={s}>{s}</option>)}</Form.Select></div><div className="uc-ticket-list">{visible.map(c => <Link key={c._id} to={`/home/status/${c._id}`}><span><b>{c.name}</b><small>{c.city}, {c.state} · {c.comment}</small></span><Badge className={statusClass(c.status)}>{c.status}</Badge></Link>)}{!visible.length && <p className="uc-empty">No matching complaints found.</p>}</div></> : <div className="uc-coming"><AreaChart size={25}/><h3>{active} dashboard</h3><p>This panel is ready for your next integration.</p></div>}</section>}
      </section></main>
      <Modal centered show={showSettings} onHide={() => setShowSettings(false)}><Modal.Header closeButton><Modal.Title>Account settings</Modal.Title></Modal.Header><Modal.Body><div className="uc-modal-user"><span>{user?.name?.charAt(0)?.toUpperCase() || "U"}</span><div><b>{user?.name}</b><small>{user?.email}</small></div></div><Form.Check className="mt-4" type="switch" label="Receive complaint status updates" checked={updates} onChange={e => setUpdates(e.target.checked)}/></Modal.Body><Modal.Footer><Button variant="light" onClick={() => setShowSettings(false)}>Cancel</Button><Button onClick={() => { localStorage.setItem("complaintUpdates", updates ? "on" : "off"); setShowSettings(false); }}>Save settings</Button></Modal.Footer></Modal>
      <Modal centered show={showFeedback} onHide={() => { setShowFeedback(false); setSent(false); }}><Modal.Header closeButton><Modal.Title>Share feedback</Modal.Title></Modal.Header><Modal.Body>{sent ? <Alert variant="success" className="mb-0">Thank you! Your feedback has been recorded.</Alert> : <Form onSubmit={submitFeedback}><Form.Label>How can we improve?</Form.Label><Form.Control as="textarea" rows={5} maxLength={600} value={feedback} onChange={e => setFeedback(e.target.value)} placeholder="Write your feedback here..."/><Button type="submit" className="w-100 mt-3">Send feedback</Button></Form>}</Modal.Body></Modal>
    </div>;
}
